name       : gdb
version    : 8.3.1
release    : 11
source     :
    - https://ftp.gnu.org/gnu/gdb/gdb-8.3.1.tar.xz : 1e55b4d7cdca7b34be12f4ceae651623aa73b2fd640152313f9f66a7149757c4
homepage   : http://www.gnu.org/software/gdb/
license    : GPL-3.0-or-later
component  : programming.tools
summary    : GDB - The GNU Project Debugger
description: |
    GDB, the GNU Project debugger, allows you to see what is going on 'inside' another program while it executes, or what another program was doing at the moment it crashed.
patterns   :
    - /usr/include
    - /usr/lib64
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install -C gdb
