name       : gdb
version    : '10.2'
release    : 15
source     :
    - https://ftp.gnu.org/gnu/gdb/gdb-10.2.tar.xz : aaa1223d534c9b700a8bec952d9748ee1977513f178727e1bee520ee000b4f29
homepage   : https://www.gnu.org/software/gdb/
license    : GPL-3.0-or-later
component  : programming.tools
summary    : GDB - The GNU Project Debugger
description: |
    GDB, the GNU Project debugger, allows you to see what is going on 'inside' another program while it executes, or what another program was doing at the moment it crashed.
patterns   :
    - /usr/include
    - /usr/lib64
builddeps  :
    - pkgconfig(libxxhash)
    - pkgconfig(python3)
setup      : |
    %configure \
        --with-python=/usr/bin/python3 \
        --with-system-zlib
build      : |
    %make
install    : |
    %make_install -C gdb
    %make_install -C gdbserver
