name       : gdb
version    : 7.12.1
release    : 6
source     :
    - https://ftp.gnu.org/gnu/gdb/gdb-7.12.1.tar.xz : 4607680b973d3ec92c30ad029f1b7dbde3876869e6b3a117d8a7e90081113186
homepage   : http://www.gnu.org/software/gdb/
license    :
    - GPL-2.0
summary    : GNU Debugger
component  : programming.tools
builddeps  :
    - pkgconfig(python-2.7)
patterns   :
    - /usr/include
    - /usr/lib64
description: |
    GNU Debugger
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install -C gdb
