name       : gdb
version    : '13.1'
release    : 22
source     :
    - https://ftp.gnu.org/gnu/gdb/gdb-13.1.tar.xz : 115ad5c18d69a6be2ab15882d365dda2a2211c14f480b3502c6eba576e2e95a0
homepage   : https://www.gnu.org/software/gdb/
license    : GPL-3.0-or-later
component  : programming.tools
summary    : GDB - The GNU Project Debugger
description: |
    GDB, the GNU Project debugger, allows you to see what is going on 'inside' another program while it executes, or what another program was doing at the moment it crashed.
patterns   :
    - /usr/include
    - /usr/lib64
builddeps  :
    - pkgconfig(liblzma)
    - pkgconfig(libxxhash)
    - pkgconfig(libzstd)
    - pkgconfig(python3)
setup      : |
    %configure \
        --with-python=/usr/bin/python3 \
        --with-system-zlib
build      : |
    %make
install    : |
    %make_install -C gdb
    %make_install -C gdbserver
