name       : gdb
version    : '8.2'
release    : 10
source     :
    - https://ftp.gnu.org/gnu/gdb/gdb-8.2.tar.gz : 847e4b65e5a7b872e86019dd59659029e2b06cae962e0ef345f169dcb4b851b8
homepage   : http://www.gnu.org/software/gdb/
license    :
    - GPL-2.0
summary    : GNU Debugger
component  : programming.tools
builddeps  :
    - pkgconfig(python-2.7)
patterns   :
    - /usr/include
    - /usr/lib64
description: |
    GNU Debugger
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install -C gdb
