name       : gdb
version    : 9.1.0
release    : 12
source     :
    - https://ftp.gnu.org/gnu/gdb/gdb-9.1.tar.xz : 699e0ec832fdd2f21c8266171ea5bf44024bd05164fdf064e4d10cc4cf0d1737
homepage   : http://www.gnu.org/software/gdb/
license    : GPL-3.0-or-later
component  : programming.tools
summary    : GDB - The GNU Project Debugger
description: |
    GDB, the GNU Project debugger, allows you to see what is going on 'inside' another program while it executes, or what another program was doing at the moment it crashed.
patterns   :
    - /usr/include
    - /usr/lib64
setup      : |
    mkdir -p build/
    cd build/
    
    ../%configure
build      : |
    %make -C build
install    : |
    %make_install -C build/gdb
