name       : gdb
version    : '10.1'
release    : 13
source     :
    - https://ftp.gnu.org/gnu/gdb/gdb-10.1.tar.xz : f82f1eceeec14a3afa2de8d9b0d3c91d5a3820e23e0a01bbb70ef9f0276b62c0
homepage   : https://www.gnu.org/software/gdb/
license    : GPL-3.0-or-later
component  : programming.tools
summary    : GDB - The GNU Project Debugger
description: |
    GDB, the GNU Project debugger, allows you to see what is going on 'inside' another program while it executes, or what another program was doing at the moment it crashed.
patterns   :
    - /usr/include
    - /usr/lib64
builddeps  :
    - pkgconfig(libxxhash)
    - pkgconfig(python3)
setup      : |
    %configure \
        --with-python=/usr/bin/python3 \
        --with-system-zlib
build      : |
    %make
install    : |
    %make_install -C gdb
    %make_install -C gdbserver
