name       : gdb
version    : 8.0
release    : 7
source     :
    - https://ftp.gnu.org/gnu/gdb/gdb-8.0.tar.xz : f6a24ffe4917e67014ef9273eb8b547cb96a13e5ca74895b06d683b391f3f4ee
homepage   : http://www.gnu.org/software/gdb/
license    :
    - GPL-2.0
summary    : GNU Debugger
component  : programming.tools
builddeps  :
    - pkgconfig(python-2.7)
patterns   :
    - /usr/include
    - /usr/lib64
description: |
    GNU Debugger
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install -C gdb
